apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: app
        image: gcr.io/concrete-crow-244606/gke-test-app
        ports:
        - containerPort: 8080
