apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-app
